# Generated by Django 2.2 on 2019-04-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190413_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='docfile',
        ),
    ]
